# Generated by Django 5.1.2 on 2024-12-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pergunta_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
